server:
    dockerfile: $PWD/docker/server/Dockerfile
    build: $PWD/docker/server
    working_dir: /var/www/html/dockercentos
    links:
        - mysql:mysql.local
        - memcached
    ports:
        - "80:80"
        - "3000:3000"
    volumes:
        - $PWD:/var/www/html/dockercentos
        - dockercentos-server:/var/www/html
    environment:
        - PROJECT_HOST_ENV=dockercentos.dev
        - MYSQL_DATABASE=dockercentos
        - MYSQL_USER=dockercentos
        - MYSQL_PASSWORD=dockercentos
        - MYSQL_ROOT_PASSWORD=dockercentos

mysql:
    dockerfile: $PWD/docker/db/Dockerfile
    build: $PWD/docker/db
    ports:
        - "3306:3306"
    environment:
        - MYSQL_DATABASE=dockercentos
        - MYSQL_USER=dockercentos
        - MYSQL_PASSWORD=dockercentos
        - MYSQL_ROOT_PASSWORD=dockercentos
    volumes:
        - $PWD/docker/db/init.d:/docker-entrypoint-initdb.d
        - dockercentos-mysql:/var/lib/mysql
    mem_limit: 1000000000

memcached:
  image: memcached
  volumes:
    - dockercentos-memcached:/etc/sysconfig/memcached